# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI Build and test status

on:
  push:
    branches: [ "main", "dev", "feature/middleware" ]
  pull_request:
    branches: [ "main" , "dev", "feature/middleware"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.12.0'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
      working-directory: ./

    - name: Run build
      run: npm run build --if-present
      working-directory: ./

    - name: Run tests
      env:
        GOOGLE_CLIENT_ID: "test"
        GOOGLE_CLIENT_SECRET: "test"
      run: npm test -- --coverage
      working-directory: ./

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: SparkRunners/user-server-service

